---

- hosts: all
  become: true
  gather_facts: yes
  tasks:
  - name: updat repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
        
  - name: install nginx package
    apt:
      name: nginx
      state: latest
    when: ansible_distribution == "Ubuntu"


