---

- hosts: all
  become: true
  gather_facts: yes
  tasks:

#update apt
  - name: update apt repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
        
  - name: install nginx package
    apt:
      name: nginx
      state: latest
    when: ansible_distribution == "Ubuntu"

#update yum
  - name: update yum repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

