---


- hosts: all
  become: true
  gather_facts: yes
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: install nginx and php-fpm packages on (Ubuntu)
    tags: nginx,php-fpm,ubuntu
    apt:
      name: 
        - nginx
        - php-fpm
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site (Ubuntu)
    tags: nginx,ubuntu
    copy:
      src: default_site.html
      dest: /usr/share/nginx/html/index.html 
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "Ubuntu"
    register: nginx

  - name: restart nginx (Ubuntu)
    tags: nginx,ubuntu,service
    service:
      name: nginx
      state: restarted
      enabled: yes
    when: nginx.changed

  - name: install httpd and php  packages on (CentOS)
    tags: httpd,php,centos
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin user (CentOS)
    tags: httpd,centos
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@mail.com
    when: ansible_distribution == "CentOS"
    register: httpd_email

  - name: copy default html file for site (CentOS)
    tags: httpd,centos
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "CentOS"
    register: httpd_index 

  - name: start httpd (CentOS)
    tags: httpd,centos
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: restart httpd (CentOS)
    tags: httpd,centos
    service:
      name: httpd
      state: restarted
    when: httpd_email.changed or httpd_index.changed


- hosts: MySQL_db
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba


