---

- hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: install nginx and php-fpm packages (Ubuntu)
    apt:
      name: 
        - nginx
        - php-fpm
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php packages (CentOS)
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

